# Generated by Django 4.1.3 on 2024-07-28 12:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('company_name', models.CharField(default='', max_length=30, unique=True)),
                ('contact_person', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=30, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('business_licence_number', models.CharField(default='', max_length=30, unique=True)),
                ('profile_pic', models.ImageField(blank=True, default='default1.jpg', null=True, upload_to=main.models.profile_pics_upload_path)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('total_seats', models.IntegerField(blank=True, default=0, null=True)),
                ('number_plate', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('seat_picture', models.ImageField(blank=True, null=True, upload_to='media/buses/')),
            ],
        ),
        migrations.CreateModel(
            name='DriverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('license_number', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('nrc_number', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('passport_number', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='media/license_image/')),
                ('nrc_image', models.ImageField(blank=True, null=True, upload_to='media/nrc_image/')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='media/passport_image/')),
                ('user', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, default='', max_length=30)),
                ('destination', models.CharField(blank=True, default='', max_length=30)),
                ('departure_date', models.DateTimeField(default=datetime.datetime.now)),
                ('departure_time', models.TimeField(default=datetime.time(12, 0))),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trip_status', models.CharField(blank=True, default='Upcoming', max_length=30, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bus')),
                ('driver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.driverdetails')),
                ('user', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(default='', max_length=255, null=True)),
                ('passenger_phonenumber', models.CharField(max_length=255)),
                ('passenger_email', models.CharField(default='', max_length=255)),
                ('seat_number', models.CharField(default='', max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('buyer_user_id', models.IntegerField(default=0)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('bus', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.bus')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tripschedule')),
                ('user', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('features', models.ManyToManyField(blank=True, to='main.feature')),
                ('user', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='features',
            field=models.ManyToManyField(blank=True, to='main.feature'),
        ),
        migrations.AddField(
            model_name='bus',
            name='user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
