# Generated by Django 4.1.3 on 2024-04-11 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(blank=True, choices=[], default='', max_length=30)),
                ('total_seats', models.IntegerField(blank=True, default=0)),
                ('number_plate', models.CharField(blank=True, choices=[], default='', max_length=7)),
                ('features', models.CharField(blank=True, choices=[('wifi', 'WiFi'), ('tv', 'TV'), ('snacks', 'Snacks')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('seat_picture', models.ImageField(blank=True, null=True, upload_to='media/buses/')),
            ],
        ),
        migrations.CreateModel(
            name='TripSchdule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, default='', max_length=30)),
                ('departure', models.CharField(blank=True, default='', max_length=30)),
                ('departure_date', models.DateTimeField(default=datetime.datetime.now)),
                ('departure_time', models.TimeField(default=datetime.time(12, 0))),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bus')),
            ],
        ),
    ]
