# Generated by Django 4.1.3 on 2024-04-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bus_tripschdule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TripSchdule',
            new_name='TripSchedule',
        ),
    ]
