# Generated by Django 4.1.3 on 2024-04-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='number_plate',
            field=models.CharField(blank=True, choices=[], default='', max_length=10),
        ),
    ]
