# Generated by Django 4.1.3 on 2024-04-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tripschedule_price_alter_bus_number_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Wifi', 'WiFi'), ('Tv', 'TV'), ('Snacks', 'Snacks')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='features',
        ),
        migrations.AddField(
            model_name='bus',
            name='features',
            field=models.ManyToManyField(blank=True, to='main.feature'),
        ),
    ]
