# Generated by Django 4.1.3 on 2024-04-13 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_feature_remove_bus_features_bus_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
