# Generated by Django 4.1.3 on 2024-04-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_feature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='features',
            field=models.ManyToManyField(blank=True, to='main.feature'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_feature_name'),
        ),
    ]
