# Generated by Django 4.1.3 on 2024-04-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_bus_bus_type_alter_bus_number_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
