# Generated by Django 4.1.3 on 2024-04-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_bus_bus_type_alter_bus_number_plate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='unique_feature_name',
        ),
        migrations.RenameField(
            model_name='tripschedule',
            old_name='departure',
            new_name='destination',
        ),
    ]
