# Generated by Django 4.1.3 on 2024-04-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_passenger_age_ticket_passenger_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passenger_email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
