# Generated by Django 4.1.3 on 2024-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_ticket_passenger_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passenger_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger_phonenumber',
            field=models.CharField(max_length=255),
        ),
    ]
