# Generated by Django 4.1.3 on 2024-04-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_ticket_passenger_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passenger_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
