# Generated by Django 4.1.3 on 2024-04-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_bus_is_seat_booked_bus_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seat_number',
            field=models.IntegerField(default=0),
        ),
    ]
