# Generated by Django 4.1.3 on 2024-04-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_bus_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='is_seat_booked',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seats',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bus')),
            ],
        ),
    ]
