# Generated by Django 4.1.3 on 2024-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_bus_is_seat_booked_remove_bus_seat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='buyer_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
