# Generated by Django 4.1.3 on 2024-05-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_ticket_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripschedule',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.driverdetails'),
        ),
    ]
